version: '3.8'

services:
  web_service:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start
    restart: always
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - env/.env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/www/static
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web_service

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - /var/certbot/www/:/var/www/certbot/:rw
    depends_on:
      - nginx

  db:
    image: postgres:15-alpine
    container_name: restaurant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restaurant
      - POSTGRES_PASSWORD=1253
    ports:
      - "5432:5432"

volumes:
  media_volume:
  static_volume:
  postgres_data:
