# Generated by Django 5.0.3 on 2024-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menu_options_alter_menu_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="youtube_video",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
