# Generated by Django 5.0.3 on 2024-04-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_home_youtube_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="youtube_video",
            field=models.CharField(max_length=800),
        ),
    ]
