# Generated by Django 5.0.3 on 2024-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_home_youtube_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/static/image/black_logo.png",
                null=True,
                upload_to="services/",
            ),
        ),
    ]
