#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Apply Django migrations
python manage.py makemigrations
python manage.py migrate --noinput

# Collect static files
python manage.py collectstatic --noinput

gunicorn --config /app/gunicorn_config.py core.wsgi:application

certbot --nginx --non-interactive --agree-tos --email jahongirhakimjonov@gmail.com --domains shinzofamily.uz


# Run Gunicorn server
#exec gunicorn core.wsgi:application --bind 0.0.0.0:8000
